server:
  port: 8080

spring:
  application:
    name: iorder
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8848,192.168.1.3:8858,192.168.1.3:8868
        register-enabled: true
        group: DEFAULT_GROUP
        service: iorder


